// MACRO ECONOMIC DATA (2025-2026 ESTIMATES)
window.MACRO_DATA = {
    "inflation_national": 6.2,
    "repo_rate": 6.5,
    "fd_rate_avg": 7.0,
    "gold_cagr": 11.2,
    "nifty_cagr": 12.5,
    "real_estate_cagr": 8.0
};

// State-wise Inflation Estimates (Based on recent CPI trends)
window.STATE_INFLATION = {
    "Andhra Pradesh": 6.8,
    "Arunachal Pradesh": 5.5,
    "Assam": 6.1,
    "Bihar": 7.2,
    "Chhattisgarh": 6.4,
    "Goa": 4.1,
    "Gujarat": 5.8,
    "Haryana": 6.0,
    "Himachal Pradesh": 5.2,
    "Jharkhand": 6.7,
    "Karnataka": 5.9,
    "Kerala": 5.4,
    "Madhya Pradesh": 6.5,
    "Maharashtra": 6.3,
    "Manipur": 7.5,
    "Meghalaya": 6.0,
    "Mizoram": 6.2,
    "Nagaland": 5.8,
    "Odisha": 6.9,
    "Punjab": 6.1,
    "Rajasthan": 6.6,
    "Sikkim": 5.3,
    "Tamil Nadu": 5.7,
    "Telangana": 6.8,
    "Tripura": 5.9,
    "Uttar Pradesh": 7.0,
    "Uttarakhand": 5.5,
    "West Bengal": 6.4,
    "Delhi": 5.6,
    "Jammu & Kashmir": 6.2,
    "Ladakh": 6.0,
    "Puducherry": 5.1,
    "Andaman & Nicobar": 5.8,
    "Chandigarh": 5.9,
    "Dadra & Nagar Haveli": 5.5,
    "Lakshadweep": 6.5
};

// Cost of Living Multiplier (Previously in data_engine, now aligned here)
window.STATE_MULTIPLIERS = {
    "Maharashtra": 0.88,
    "Delhi": 0.85,
    "Karnataka": 0.90,
    "Tamil Nadu": 0.92,
    "Uttar Pradesh": 1.10,
    "Bihar": 1.15,
    "West Bengal": 1.05,
    "Rajasthan": 1.08,
    "Gujarat": 0.95,
    "Kerala": 0.95,
    "Punjab": 1.00,
    "Haryana": 0.98,
    "Madhya Pradesh": 1.12,
    "Odisha": 1.14,
    "Andhra Pradesh": 1.02,
    "Telangana": 0.98,
    "Assam": 1.10,
    "Jharkhand": 1.13,
    "Chhattisgarh": 1.12,
    "Himachal Pradesh": 1.05,
    "Uttarakhand": 1.06,
    "Goa": 0.90,
    "Tripura": 1.15,
    "Meghalaya": 1.10,
    "Manipur": 1.15,
    "Nagaland": 1.15,
    "Arunachal Pradesh": 1.12,
    "Mizoram": 1.15,
    "Sikkim": 1.08,
    "Jammu & Kashmir": 1.05
};
